# -*- coding: utf-8 -*-
"""Gold_Price_Predictor_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1INm1LH8V4GEwCdgXeoxm1zObwq_-JXoX
"""

# Install the library to get data (run this only once)
!pip install yfinance

import yfinance as yf
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

print("Libraries Loaded. Ready to conquer the market.")

# Define our tickers (GLD = Gold, SPY = Stocks, USO = Oil, EURUSD=X = Forex)
tickers = ['GLD', 'SPY', 'USO', 'EURUSD=X']

# 1. DOWNLOAD data from 2008 to today
df = yf.download(tickers, start='2008-01-01')['Close']

# 2. CLEANUP: Drop any empty rows (N/A)
df = df.dropna()

# 3. PREVIEW the first 5 rows
print(df.head())

# 1. Calculate Daily Returns (Percent Change)
# This replaces the "(Today - Yesterday) / Yesterday" formula
returns = df.pct_change().dropna()

# 2. Create "Features" (X) and "Target" (y)
# We use .shift(1) to create the "Lag" (Yesterday's data)
# Ideally, we want to predict Gold (GLD) using yesterday's market info.
X = returns[['SPY', 'USO', 'EURUSD=X']].shift(1).dropna()
y = returns['GLD'].iloc[1:]  # Align y with the shifted X

# 3. Double check the alignment
print("Features (X) - Yesterday's Returns:")
print(X.tail())
print("\nTarget (y) - Today's Gold Return:")
print(y.tail())

# Set up the plotting figure size
plt.figure(figsize=(10, 8))

# Create the Heatmap
# annot=True adds the numbers inside the boxes
# cmap='coolwarm' makes positive correlations red and negative blue
sns.heatmap(returns.corr(), annot=True, cmap='coolwarm', fmt='.2f')

# Add a title
plt.title('Correlation Matrix: Global Assets vs Gold')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# 1. SPLIT the data
# We hide 20% of the data (test_size=0.2) to simulate "The Future"
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

print(f"Training Data: {len(X_train)} days")
print(f"Testing Data: {len(X_test)} days (This is our 'Future')")

# 2. BUILD the Model
# n_estimators=100 means "Create 100 different economists (trees) and average their opinions"
model = RandomForestRegressor(n_estimators=100, random_state=42)

# 3. TRAIN (Fit) the model on the past data
model.fit(X_train, y_train)

# 4. PREDICT the future (on the hidden Test set)
predictions = model.predict(X_test)

print("Model Trained. AI Economist is ready.")

# Create a DataFrame to compare Real vs Predicted
results = pd.DataFrame({'Actual': y_test, 'Predicted': predictions}, index=y_test.index)

# Plot the last 100 days (to see clearly)
plt.figure(figsize=(12, 6))
plt.plot(results['Actual'].tail(100), label='Actual Market', color='blue', alpha=0.6)
plt.plot(results['Predicted'].tail(100), label='AI Prediction', color='red', linestyle='--')
plt.title('AI Gold Price Prediction (Last 100 Days)')
plt.legend()
plt.show()

# How close were we? (Mean Absolute Error)
error = mean_absolute_error(y_test, predictions)
print(f"Average Error: {error:.4f} (This is your average daily miss in %)")

# Create a DataFrame to compare Real vs Predicted
results = pd.DataFrame({'Actual': y_test, 'Predicted': predictions}, index=y_test.index)

# Plot the last 100 days (to see clearly)
plt.figure(figsize=(12, 6))
plt.plot(results['Actual'].head(100), label='Actual Market', color='blue', alpha=0.6)
plt.plot(results['Predicted'].head(100), label='AI Prediction', color='red', linestyle='--')
plt.title('AI Gold Price Prediction (Last 100 Days)')
plt.legend()
plt.show()

# How close were we? (Mean Absolute Error)
error = mean_absolute_error(y_test, predictions)
print(f"Average Error: {error:.4f} (This is your average daily miss in %)")

# Function to calculate RSI (Relative Strength Index)
def calculate_rsi(data, window=14):
    delta = data.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=window).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=window).mean()
    rs = gain / loss
    return 100 - (100 / (1 + rs))

# 1. Add RSI to our Main Data
df_features = pd.DataFrame(index=df.index)
df_features['RSI'] = calculate_rsi(df['GLD'])

# 2. Add Volatility (Standard Deviation of last 20 days)
df_features['Volatility'] = df['GLD'].pct_change().rolling(window=20).std()

# 3. Add our old friends (Lagged Returns)
df_features['Gold_Lag1'] = df['GLD'].pct_change().shift(1)
df_features['Oil_Lag1'] = df['USO'].pct_change().shift(1)
df_features['Stock_Lag1'] = df['SPY'].pct_change().shift(1)

# 4. Cleanup
df_features = df_features.dropna()
y_target = df['GLD'].pct_change().loc[df_features.index]

print("New Features Created:")
print(df_features.tail())

# 1. Split again (New Data)
X_train_v2, X_test_v2, y_train_v2, y_test_v2 = train_test_split(df_features, y_target, test_size=0.2, shuffle=False)

# 2. Train the Enhanced Model
model_v2 = RandomForestRegressor(n_estimators=100, min_samples_leaf=5, random_state=42)
model_v2.fit(X_train_v2, y_train_v2)

# 3. Predict
predictions_v2 = model_v2.predict(X_test_v2)

# 4. Check Feature Importance (What does the AI care about?)
importance = pd.Series(model_v2.feature_importances_, index=df_features.columns)
importance.sort_values().plot(kind='barh', title="What drives Gold Prices?")
plt.show()

